enum StructureTypeEnum {
  CASA_DI_CURA = 1,
  CENTRO_ODONTOIATRICO = 2,
  OSPEDALE = 3,
  POLICLINICO_UNIVERSITARIO = 4,
  POLIAMBULATORIO_DIAGNOSTICO = 5,
  CENTRO_FISIOTERAPICO = 6,
  LABORATORIO_ANALISI = 7
}

export default StructureTypeEnum
